name: publish
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  publish_nuget_package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Use .NET 8.0 as .NET 9.0 is not supported
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
    - name: Pack xUnitLoadFramework
      run: dotnet pack src/xUnitLoadFramework/xUnitLoadFramework.csproj --configuration Release --output ${{ env.NuGetDirectory }} --no-build /bl
    - name: Setup NuGet CLI
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '1.0.0-alpha.${{ github.run_number }}' # Specify the desired version of NuGet CLI
    - name: Publish to NuGet
      run: dotnet nuget push ${{ env.NuGetDirectory }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json